#!/usr/bin/env python3
"""Generate one synthetic KORA Core evidence run record."""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from kora_core.harness import load_request_fixtures, run_request_harness  # noqa: E402
from kora_core.run_record import create_run_record_from_harness, write_run_record  # noqa: E402


def _git_commit() -> str | None:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def main() -> int:
    fixture_path = REPO_ROOT / "tests" / "fixtures" / "sample_requests.json"
    requests = load_request_fixtures(fixture_path)
    harness_output = run_request_harness(requests)
    record = create_run_record_from_harness(
        harness_output,
        requests=requests,
        run_name="KORA Core v0.1 synthetic fixture run",
        git_commit=_git_commit(),
        environment_label="local-synthetic",
        workload_id="sample_requests_v0_1",
        workload_name="KORA Core synthetic sample requests",
        workload_source="tests/fixtures/sample_requests.json",
        notes=["Generated by scripts/record_synthetic_evidence.py with no external calls."],
    )
    filename = f"{datetime.now(UTC).strftime('%Y%m%d-%H%M%S')}-synthetic-kora-core.json"
    output_path = REPO_ROOT / "docs" / "evidence" / "runs" / filename
    write_run_record(record, output_path)

    summary = {
        "evidence_path": str(output_path.relative_to(REPO_ROOT)),
        "total_requests": record.routing.total_requests,
        "routing_distribution": record.routing.routing_percentages,
        "avoided_provider_calls": record.provider.avoided_provider_calls,
        "claim_level": str(record.evidence_status.claim_level),
        "warnings": record.evidence_status.claim_warnings,
    }
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
